# SPDX-FileCopyrightText: The unnest authors
# SPDX-License-Identifier: CC0-1.0

overrides:
  - files:
      - "**/*.yaml"
      - "**/*.yml"
    options:
      tabWidth: 2
      # in double quotes you can use escapes
      singleQuote: false
